### ISSUE TITLE
Can not install plugin

### ISSUE THREAD

**Issue by paulfcdd** [BitBagCommerce/SyliusInPostPlugin#23]
Which version of Sylius is required for this plugin? I have fresh installed Sylius app version 1.12.11 and your plugin is failed to install

![Screenshot from 2023-10-04 14-08-58](https://github.com/BitBagCommerce/SyliusInPostPlugin/assets/11246832/cabaf881-d327-4f01-acb5-79602da6b299)

**Comment by JanPalen** [comment]
When you tried to install that plugin, it required Sylius version 1.9.0 or 1.10.0, as you can see in the screenshot above. Currently, the plugin requires versions 1.11.0 or 1.12.0. 

However, the newest version, which will require versions 1.12.0 or 1.13.0, is set to be released in a month.
